# Generated by Django 5.0.7 on 2024-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_datetimemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_utc', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='datetimemodel',
            name='is_utc',
            field=models.BooleanField(default=False),
        ),
    ]
