# Generated by Django 5.0.7 on 2024-07-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_conversionstate_datetimemodel_is_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimemodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
