# Generated by Django 5.0.7 on 2024-07-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_datetimemodel_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversionState',
        ),
    ]
